### ISSUE TITLE
Ticket Classes

### ISSUE THREAD

**Issue by Shafeman** [Shafeman/BarbarianTheater#2]
Still would need formatting to have the correct change, ie ($4.23 not $4.233339)

**Comment by ghost** [comment]
just added the formatting the the ticket classes. Just needs testing before we close this issue.

**Comment by Shafeman** [comment]
This is still an issue on the return method for the UI formatting. Still shows up as $50.0.  I didn't test it for something like $50.123...

**Comment by ghost** [comment]
Money is now represented as an Integer which is a representation of
cents on a dollar. 100 cents = $1.00. There is a static method in the UI
(displayPrice()) for the purpose of diplaying a price. ie. $4.34 not
$434

**Comment by ghost** [comment]
When listing tickets we get:

09/20/2015  9201507R $3.00 Regular
09/20/2015  9201508A $2.10 Advance
09/20/2015  9201509S $1.5 Student Advance _Must show valid student id_

formatting is still an issue

**Comment by ghost** [comment]
Student price should be $1.05, not $1.5

**Comment by ghost** [comment]
Fixed so far: 

09/20/2015  9201507R $3.00 Regular
09/20/2015  9201508A $2.10 Advance
09/20/2015  9201509S $1.05 Student Advance _Must show valid student id_

made some changes in displayPrice() is UI

**Comment by Shafeman** [comment]
displayPrice should not be in UI. Ticket uses it in its toString, giving us really bad coupling.
Also, if a ticket price of 3 is entered, it is saved as $0.03. If a ticket price of 8.523 is entered, it is saved as $85.23. So the ticket prices still isn't working.

**Comment by Shafeman** [comment]
Any thought on using BigDecimal instead of int? I think to use int we'll need to separate dollars and cents. It sounds like BigDecimal handles rounding pretty well and is commonly used for money.

**Comment by ghost** [comment]
Switched all Integers to BigDecimal.

**Comment by ghost** [comment]
With BigDecimal, when rounding and using MathContex(x). If the balance or price is < 100 use MathContext(3), if it is >= 100 use MathContext(4) if it is >= 1000 use MathContext(5) ect...

I have yet to get a chance to read more into the BigDecimal and rounding.. as it is right now, rounding still needs work

**Comment by kangn** [comment]
well i set the price of 8.523 and the sales of:
regular: 8.52
advance: 5.97  (8.52 \* .7 = 5.964) or the value saved would be (8.523 \* .7 = 5.9661)
Student: 2.98  (5.97 \* .5 = 2.98)
I do see that the rounding is off just a tad bit because the extra .003 bit didn't get dropped off. I'm not sure this is really a big problem being that its just a penny and we are in control of the sales. I think this issue is closed thoughts?
